name: Build release zip

on:
  push:
    tags:
    - '*'

permissions:
  contents: write  # needed to create releases and upload assets

jobs:
  build:
    name: Build release zip
    runs-on: ubuntu-latest
    steps:
    
    # Checkout the code from the repository
    - name: Checkout
      uses: actions/checkout@v4

    # Create the zip file using https://github.com/marketplace/actions/zip-release
    - name: Zip Release
      uses: TheDoctor0/zip-release@0.7.6
      with:
        type: 'zip'
        filename: 'woo-multicaixa.zip' # Name of the archive file
        exclusions: ' *.git* *.github* /*node_modules* .distignore .gitignore .phpcs.xml.dist README.md createzip.command package-lock.json package.json webpack.config.js' # Would be great to get this automatically from .distignore
    
    # Create release and upload the zip file as an asset using https://github.com/marketplace/actions/gh-release
    - name: Publish Release
      uses: softprops/action-gh-release@v2.3.3
      with:
        tag_name: ${{ github.ref_name }}
        name: ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: woo-multicaixa.zip